slam_toolbox:
  ros__parameters:
    slam_mode: true
    resolution: 0.05
    map_update_interval: 2.0
    publish_map: true
    publish_pose: true
    map_start_pose: [0.0, 0.0, 0.0]
    map_topic: /map
